name: event_search
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  retrofit_generator: ^9.1.9
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
